pipeline {
    agent any
    environment{
        		IMAGE_NAME = "omarnajar/employee_frontend"
    }
    stages {

        stage ('build docker '){
            steps{
                bat 'docker --help'
            }
        }
        stage ('build docker image from dockerfile'){
            steps{
                echo 'start building'
                bat 'docker build -t ${IMAGE_NAME}:${GIT_COMMIT} -t ${IMAGE_NAME}:latest EmployeeProjectFront'
            }
        }

        stage ('login to omar dockerhub'){
            steps{
                bat 'docker login -u $USER -p $PASSWORD'
            }
        }

        stage ('push image to omar dockerhub'){
            steps{
                bat 'docker push $IMAGE_NAME:$GIT_COMMIT'
            }
        }

        stage ('run docker container'){
             steps{
                  bat 'docker run -d -p 82:80 $IMAGE_NAME:latest'
             }
}
}
}