pipeline {
    agent any
    environment{
        		IMAGE_NAME = "omarnajar/employee_frontend"
                KUBECONFIG_PATH = "C:\\Users\\najar\\.kube\\config"
    }
    stages {
        stage ('build docker image from dockerfile'){
            steps{
                 script {
                    // Get the short Git commit hash
                    GIT_COMMIT = bat(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
                }
                bat 'docker build -t %IMAGE_NAME%:%GIT_COMMIT% -t %IMAGE_NAME%:latest EmployeeProjectFront'
            }
        }

        stage ('login to omar dockerhub'){
            steps{
                bat 'docker login -u %USER% -p %PASSWORD%'
            }
        }

        stage ('push image to omar dockerhub'){
            steps{
                bat 'docker push %IMAGE_NAME%:%GIT_COMMIT%'
            }
        }

        stage('Deploy to kube') {
            environment {
                
                DEPLOY_IMAGE = "%IMAGE_NAME%:%GIT_COMMIT%"
            }
            steps {
                script {
                    
                    bat "kubectl --kubeconfig=%KUBECONFIG_PATH% set image deployment/my-dep employee-frontend-s9cm9=%DEPLOY_IMAGE%"
                }
            }
        }

}
}
