apiVersion: v1
kind: Service
metadata:
  name: dep-backend-service
  labels:
    app: dep-backend
spec:
  type: ClusterIP
  selector:
    app: dep-backend
    tier: back
  ports:
    - port: 8080
      targetPort: 8080
