apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dep-backend
  name: dep-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dep-backend
      tier: back
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dep-backend
        tier: back
    spec:
      containers:
      - image: omarnajar/employee_backend:5bde38f541064e6a22222be1fddf8b0ca11f9091
        name: employee-backend-knr88
        env:
        - name:  SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-service:5432/postgres
        - name:  SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name:  SPRING_DATASOURCE_PASSWORD
          value: "password"
        - name:  SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo waiting for database; sleep 5; done;']

        resources: {}
status: {}
