apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: depdatabase
  name: depdatabase
spec:
  replicas: 3
  selector:
    matchLabels:
      app: depdatabase
      tier: database
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: depdatabase
        tier: database
    spec:
      containers:
      - image: postgres:14
        name: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_DB
          value: "postgres"
        resources: {}
status: {}